
spring:
  application:
    name: clickhouse-spring-data-demo
  datasource:
    username: admin
    password: admin
    url: "jdbc:mysql://localhost:9004/spring_demo?serverTimezone=UTC"

  jpa:
    show-sql: true
